from .UsuarioSerializer import UsuarioSerializar
from .PedidoSerializer import PedidoSerializers
from .EnderecoSerializer import EnderecoSerializers
from .EnderecoUsuarioSerializer import EnderecoUsuarioSerializer
from .ProdutoSerializer import ProdutoSerializers
from .AvaliacaoSerializer import AvaliacaoSerializers