FROM node:20.10-alpine

WORKDIR /frontend

COPY package-lock.json .
COPY package.json .
COPY tsconfig.json .
COPY tsconfig.node.json .
COPY vite.config.ts .

RUN npm install
ENV PATH="/frontend/node_modules/.bin:$PATH"

COPY src src
COPY index.html .

COPY start.local.sh ./start.local.sh
RUN chmod +x ./start.local.sh
CMD ./start.local.sh
