# Generated by Django 4.2.7 on 2023-11-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanas', '0002_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='produto',
            new_name='usuario',
        ),
    ]
