# Generated by Django 4.2.7 on 2023-11-30 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('americanas', '0004_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.FloatField()),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='EnderecoUsuario',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_endereco', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('endereco_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='americanas.endereco')),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='americanas.usuario')),
            ],
            options={
                'db_table': 'endereco_usuario',
            },
        ),
    ]
