# Generated by Django 4.2.7 on 2023-11-30 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('americanas', '0005_produto_enderecousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo_avaliacao', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('nota', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanas.produto')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
    ]
